# Generated by Django 4.0.3 on 2022-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64)),
                ('user_pw', models.CharField(max_length=64)),
                ('last_sign_on', models.DateTimeField()),
            ],
        ),
    ]
