# Generated by Django 4.0.3 on 2022-04-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
