# Generated by Django 4.0.3 on 2022-04-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('scientific', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('alive', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tree',
                'managed': False,
            },
        ),
    ]
